dpkg-deb expects dirs with 755 to avoid:
error: control directory has bad permissions 777 (must be >=0755 and <=0775)

https://tldp.org/HOWTO/html_single/Debian-Binary-Package-Building-HOWTO/#AEN92