libs needed to avoid link errors like:
undefined reference to symbol uncompress
error adding symbols: DSO missing from command line

taken from 9544f72842b1b